'use client'

import { useState } from 'react'
import LegalLayout from '@/components/legal/LegalLayout'
import { LegalAccordion } from '@/components/legal/LegalAccordion'
import { Header } from '@/app/components/Header'
import { Footer } from '@/app/components/Footer'

const sections = [
  {
    id: 'acceptance-of-terms',
    title: '1. Acceptance of Terms',
    content: (
      <>
        <p>By accessing or using Culi (&quot;the Service&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you disagree with any part of these terms, you may not access the Service.</p>
        
        <p className="mt-4">These Terms apply to all visitors, users, and others who access or use the Service, including:</p>
        <ul>
          <li>Restaurant owners and staff (&quot;Restaurant Users&quot;)</li>
          <li>Restaurant guests and visitors (&quot;Guests&quot;)</li>
        </ul>
      </>
    )
  },
  {
    id: 'description-of-service',
    title: '2. Description of Service',
    content: (
      <>
        <p>Culi provides an AI-powered menu assistant service that enables:</p>
        <ul>
          <li>Restaurants to upload and manage their menus digitally</li>
          <li>Guests to scan QR codes and ask questions about menu items</li>
          <li>Multi-language support for menu inquiries</li>
          <li>Analytics and insights for restaurant owners</li>
        </ul>

        <p className="mt-4">The Service is provided &quot;as is&quot; and we reserve the right to modify, suspend, or discontinue any aspect of the Service at any time.</p>
      </>
    )
  },
  {
    id: 'user-accounts',
    title: '3. User Accounts',
    content: (
      <>
        <h4>Restaurant Accounts:</h4>
        <ul>
          <li>You must provide accurate and complete registration information</li>
          <li>You are responsible for maintaining the security of your account</li>
          <li>You must notify us immediately of any unauthorized access</li>
          <li>You are responsible for all activities under your account</li>
        </ul>

        <h4 className="mt-4">Guest Access:</h4>
        <ul>
          <li>No account required for basic menu inquiries</li>
          <li>Guest sessions are temporary and anonymized</li>
          <li>Optional features may require providing additional information</li>
        </ul>
      </>
    )
  },
  {
    id: 'acceptable-use',
    title: '4. Acceptable Use Policy',
    content: (
      <>
        <p>You agree not to use the Service to:</p>
        <ul>
          <li>Violate any laws or regulations</li>
          <li>Upload false, misleading, or harmful content</li>
          <li>Infringe on intellectual property rights</li>
          <li>Harass, abuse, or harm others</li>
          <li>Attempt to gain unauthorized access to the Service</li>
          <li>Use the Service for any illegal or unauthorized purpose</li>
          <li>Interfere with or disrupt the Service</li>
          <li>Reverse engineer or attempt to extract source code</li>
        </ul>
      </>
    )
  },
  {
    id: 'content-ownership',
    title: '5. Content Ownership and License',
    content: (
      <>
        <h4>Your Content:</h4>
        <ul>
          <li>You retain all rights to content you upload (menus, images, etc.)</li>
          <li>You grant us a license to use, display, and process your content to provide the Service</li>
          <li>You represent that you have the right to upload all content</li>
        </ul>

        <h4 className="mt-4">Our Content:</h4>
        <ul>
          <li>The Service, including its design, features, and functionality, is owned by Culi</li>
          <li>Our content is protected by copyright, trademark, and other laws</li>
          <li>You may not copy, modify, or distribute our content without permission</li>
        </ul>

        <h4 className="mt-4">AI-Generated Content:</h4>
        <ul>
          <li>Responses generated by our AI are provided for informational purposes</li>
          <li>We do not guarantee the accuracy of AI-generated content</li>
          <li>You should verify important information independently</li>
        </ul>
      </>
    )
  },
  {
    id: 'payment-terms',
    title: '6. Payment Terms',
    content: (
      <>
        <p>For paid subscriptions:</p>
        <ul>
          <li>Billing occurs in advance on a monthly or annual basis</li>
          <li>All payments are processed securely through Stripe</li>
          <li>Prices are subject to change with 30 days notice</li>
          <li>No refunds for partial billing periods</li>
          <li>You must provide current, complete payment information</li>
        </ul>

        <h4 className="mt-4">Free Trial:</h4>
        <ul>
          <li>Free trials are offered at our discretion</li>
          <li>You may be required to enter payment information to start a trial</li>
          <li>You will be charged when the trial period ends unless you cancel</li>
        </ul>
      </>
    )
  },
  {
    id: 'termination',
    title: '7. Termination',
    content: (
      <>
        <p>We may terminate or suspend your account immediately, without prior notice, for:</p>
        <ul>
          <li>Breach of these Terms</li>
          <li>Violation of our Acceptable Use Policy</li>
          <li>Non-payment of fees</li>
          <li>Any conduct we deem harmful to the Service or other users</li>
        </ul>

        <p className="mt-4">Upon termination:</p>
        <ul>
          <li>Your right to use the Service ceases immediately</li>
          <li>We may delete your account and associated data</li>
          <li>You remain liable for any outstanding fees</li>
        </ul>
      </>
    )
  },
  {
    id: 'disclaimers-warranties',
    title: '8. Disclaimers and Warranties',
    content: (
      <>
        <p>THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTY OF ANY KIND. WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING:</p>
        <ul>
          <li>MERCHANTABILITY</li>
          <li>FITNESS FOR A PARTICULAR PURPOSE</li>
          <li>NON-INFRINGEMENT</li>
          <li>ACCURACY OR RELIABILITY OF INFORMATION</li>
        </ul>

        <p className="mt-4">We do not warrant that:</p>
        <ul>
          <li>The Service will be uninterrupted or error-free</li>
          <li>Defects will be corrected</li>
          <li>The Service is free of viruses or harmful components</li>
          <li>AI-generated responses will be accurate or appropriate</li>
        </ul>
      </>
    )
  },
  {
    id: 'limitation-liability',
    title: '9. Limitation of Liability',
    content: (
      <>
        <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, CULI SHALL NOT BE LIABLE FOR:</p>
        <ul>
          <li>INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES</li>
          <li>LOSS OF PROFITS, DATA, USE, OR GOODWILL</li>
          <li>SERVICE INTERRUPTIONS OR DELAYS</li>
          <li>ANY DAMAGES ARISING FROM YOUR USE OF THE SERVICE</li>
        </ul>

        <p className="mt-4">Our total liability shall not exceed the amount paid by you in the past twelve months or $100, whichever is greater.</p>
      </>
    )
  },
  {
    id: 'indemnification',
    title: '10. Indemnification',
    content: (
      <>
        <p>You agree to indemnify and hold harmless Culi, its affiliates, and their respective officers, directors, employees, and agents from any claims, damages, losses, or expenses (including attorney fees) arising from:</p>
        <ul>
          <li>Your use of the Service</li>
          <li>Your violation of these Terms</li>
          <li>Your violation of any third-party rights</li>
          <li>Content you upload or submit through the Service</li>
        </ul>
      </>
    )
  },
  {
    id: 'governing-law',
    title: '11. Governing Law and Disputes',
    content: (
      <>
        <p>These Terms are governed by the laws of [Your Jurisdiction], without regard to conflict of law principles.</p>
        
        <p className="mt-4">Any disputes arising from these Terms or the Service shall be resolved through:</p>
        <ul>
          <li>Good faith negotiations</li>
          <li>If negotiations fail, binding arbitration in [Your City]</li>
          <li>Small claims court for qualifying claims</li>
        </ul>

        <p className="mt-4">You waive any right to jury trial or class action proceedings.</p>
      </>
    )
  },
  {
    id: 'changes-to-terms',
    title: '12. Changes to Terms',
    content: (
      <>
        <p>We reserve the right to modify these Terms at any time. When we make changes:</p>
        <ul>
          <li>We will update the &quot;Last updated&quot; date</li>
          <li>For material changes, we will notify users via email or Service announcement</li>
          <li>Continued use after changes constitutes acceptance</li>
        </ul>

        <p className="mt-4">If you disagree with changes, you must stop using the Service.</p>
      </>
    )
  },
  {
    id: 'general-provisions',
    title: '13. General Provisions',
    content: (
      <>
        <ul>
          <li><strong>Entire Agreement:</strong> These Terms constitute the entire agreement between you and Culi</li>
          <li><strong>Severability:</strong> If any provision is found unenforceable, the remaining provisions continue in effect</li>
          <li><strong>Waiver:</strong> Failure to enforce any provision does not constitute a waiver</li>
          <li><strong>Assignment:</strong> You may not assign these Terms without our consent</li>
          <li><strong>Notice:</strong> We may provide notice via email or Service announcements</li>
        </ul>
      </>
    )
  }
]

export default function TermsOfServicePage() {
  const [openSection, setOpenSection] = useState<string>('')

  return (
    <>
      <Header />
      <main className="pt-16">
        <LegalLayout
          title="Terms of Service"
          lastUpdated="January 9, 2025"
          sections={sections}
          openAccordionSection={openSection}
          onAccordionChange={setOpenSection}
        >
          <div className="mb-8 p-6 bg-spanish-orange/5 rounded-lg border border-spanish-orange/20">
            <p className="text-lg text-eerie-black/90 leading-relaxed">
              Welcome to Culi. These Terms of Service govern your use of our AI-powered menu assistant 
              platform. By using our service, you agree to these terms. Please read them carefully.
            </p>
          </div>

          <LegalAccordion 
            sections={sections}
            value={openSection}
            onValueChange={setOpenSection}
          />
        </LegalLayout>
      </main>
      <Footer />
    </>
  )
}